# Ristretto Fish Colors
set -U fish_color_normal fff1f3
set -U fish_color_command 85dacc
set -U fish_color_keyword a8a9eb
set -U fish_color_quote f9cc6c
set -U fish_color_redirection fff1f3
set -U fish_color_end f38d70
set -U fish_color_error fd6883
set -U fish_color_param a8a9eb
set -U fish_color_comment 72696a
set -U fish_color_selection --background=403838
set -U fish_color_search_match --background=403838
set -U fish_color_operator adda78
set -U fish_color_escape a8a9eb
set -U fish_color_autosuggestion 72696a

set -U fish_pager_color_progress 72696a
set -U fish_pager_color_prefix 85dacc
set -U fish_pager_color_completion fff1f3
set -U fish_pager_color_description 72696a
set -U fish_pager_color_selected_background --background=403838
