# Nord Fish Colors
set -U fish_color_normal d8dee9
set -U fish_color_command 88c0d0
set -U fish_color_keyword b48ead
set -U fish_color_quote ebcb8b
set -U fish_color_redirection d8dee9
set -U fish_color_end d08770
set -U fish_color_error bf616a
set -U fish_color_param 81a1c1
set -U fish_color_comment 4c566a
set -U fish_color_selection --background=434c5e
set -U fish_color_search_match --background=434c5e
set -U fish_color_operator a3be8c
set -U fish_color_escape b48ead
set -U fish_color_autosuggestion 4c566a

set -U fish_pager_color_progress 4c566a
set -U fish_pager_color_prefix 88c0d0
set -U fish_pager_color_completion d8dee9
set -U fish_pager_color_description 4c566a
set -U fish_pager_color_selected_background --background=434c5e
